### ISSUE TITLE
Key

### ISSUE THREAD

**Issue by Andrelhu** [anthok/overwatch-api#11]
Hi there! Thanks for the API. It seems we need a key to connect now. Will this be available soon?

**Comment by anthok** [comment]
Thanks for the heads up! I just tried to look at their new documentation, but it looks like it is down right now. I can't give an estimate until I get a chance to look at it but it shouldn't be too bad regardless. I can maybe throw a release together for this Sunday if all goes well.

**Comment by Andrelhu** [comment]
Thank you! I'll be expecting this :)

**Comment by anthok** [comment]
Sadly it looks like Lootbox.eu is still down :(

**Comment by anthok** [comment]
Lootbox.eu has been discontinued :( 
We are working on porting the code over to OWAPI
